---
- include_role:
    name: jm1.virtual_pkg
  vars:
    package_name: "jm1-dev-openwrt"
    package_depends:
    # OpenWrt / LEDE
    # Using the Image Generator (Image Builder)
    # Ref.: https://lede-project.org/docs/user-guide/imagebuilder
    - subversion
    - build-essential
    - libncurses5-dev
    - zlib1g-dev
    - gawk
    - git
    - ccache
    - gettext
    - libssl-dev
    - xsltproc
    - wget
    - unzip
    - python
